### PR TITLE
aligned draft name with IETF rules

### PR DESCRIPTION
**Pull request by tlodderstedt**

### CODE REVIEW

**Review by danielfett — APPROVED** [review]

**Comment by Sakurann** [comment]
overtaken by PR #120. let's close this one.

**Review by Sakurann — CHANGES_REQUESTED** [review]
overtaken by PR #120, which also renamed the draft. let's close this one.

**Review by OR13 — APPROVED** [review]

**Review by awoie — APPROVED** [review]
lgtm, since we have merged PR #131 and might not merge PR #120, we should merge this.

**Comment by awoie** [comment]
@tlodderstedt can you pls resolve merge conflicts, then we can merge this PR.

**Pull request merged**
