### PR TITLE
remove requirement to have kid in cnf

### LINKED ISSUE #97: Why is kid mandatory for cnf claims?
The spec says:

> cnf
REQUIRED when Cryptographic Holder Binding is to be supported. Contains the confirmation method as defined in [[RFC7800](https://vcstuff.github.io/draft-terbu-sd-jwt-vc/draft-terbu-sd-jwt-vc.html#RFC7800)]. It SHOULD contain a JWK as defined in Section 3.2 of [[RFC7800](https://vcstuff.github.io/draft-terbu-sd-jwt-vc/draft-terbu-sd-jwt-vc.html#RFC7800)] and in this case, the kid (Key ID) member MUST be present in the JWK. For Cryptographic Holder Binding, the Holder Binding JWT in the Combined Format for Presentation MUST be signed by the key identified in this claim.

I don't see why `kid` is a MUST.
Moreover, the example in 4.3 does not include the `kid`, so either the text or the exampel is wrong.

### PR DESCRIPTION
**Pull request by bc-pi**
Closes #97

## 📑 Description
remove requirement to have kid in cnf

### CODE REVIEW

**Review by paulbastian — APPROVED** [review]

**Review by OR13 — CHANGES_REQUESTED** [review]
I think more text can be removed here...

Are we trying to prevent users from doing this: 

```json
{
      "iss": "https://server.example.com",
      "aud": "https://client.example.org",
      "exp": 1361398824,
      "cnf":{
        "kid": "dfd1aa97-6d8d-4575-a0fe-34b96de2bfad"
       }
     }
```

```json
{
      "iss": "did:example:123",
      "aud": "https://client.example.org",
      "exp": 1361398824,
      "cnf":{
        "kid": "did:example:123#key-42"
       }
     }
```

Seems like it should just say support RFC7800.

And make no recommendations on `jwk` vs `kid`

**Comment by awoie** [comment]
> I think more text can be removed here...
> 
> Are we trying to prevent users from doing this:

We are not trying to prevent that in this spec. The default should be the `jwk` cnf method but this is not what the PR changed or added. This PR just removes the requirement that the `kid` has to be in the `jwk` claim. This PR does not talk about the `kid` cnf method which is still an option.

**Review by awoie — APPROVED** [review]
lgtm

**Comment by OR13** [comment]
btw, I added a related comment here: https://github.com/w3c/vc-jwt/pull/111

**Review by Sakurann — APPROVED** [review]

**Review by tlodderstedt — APPROVED** [review]

**Review by danielfett — APPROVED** [review]

**Pull request merged**
