### PR TITLE
Change Holder Binding to Key Binding, adapt examples

### PR DESCRIPTION
**Pull request by danielfett**
Holder Binding is now more appropriately called Key Binding in SD-JWT. This PR makes the necessary changes in this specification.

### CODE REVIEW

**Review by Sakurann — APPROVED** [review]
`cryptographic key binding` -> `key binding`?

**Review by paulbastian — APPROVED** [review]

**Comment by paulbastian** [comment]
Would it be intresting to add a holder binding section that references to the options of
- claim based binding with PII (name, birthday etc)
- claim based binding with biometrics (porttrait)
- key binding (referencing to this part here)
?

**Comment by Sakurann** [comment]
my current thinking is that key binding, biometrics based binding and claim based binding solve very different problems, so I would not mix them.

**Review by OR13 — APPROVED** [review]

**Review by c2bo — APPROVED** [review]

**Review by awoie — APPROVED** [review]
Thanks for the updates!

**Comment by awoie** [comment]
@danielfett can you resolve merge conflicts, then pls merge.

**Pull request merged**
