### PR TITLE
make nbf optional

### PR DESCRIPTION
**Pull request by Sakurann**
I would personally remove it, but will not die on that hill

### CODE REVIEW

**Comment by c2bo** [comment]
Please correct me if I am wrong, but I would understand VCDM2.0 `validFrom` as a mix of `iat` and `nbf`? 
VCDM 2.0 does not have a issued at field and only defines `validFrom`. 

So my understanding would be:
- if only `iat` is defined, we set the `validFrom` to the value of `iat`
- if both are defined, we set `validFrom` to the value of `nbf` (and lose the iat information in the VCDM2.0 representation)

So either remove nbf completely or make it optional and basically overwrite iat (for the VCDM2.0) if it exists?
Does that make sense?

**Comment by awoie** [comment]
> Please correct me if I am wrong, but I would understand VCDM2.0 `validFrom` as a mix of `iat` and `nbf`? VCDM 2.0 does not have a issued at field and only defines `validFrom`.
> 
> So my understanding would be:
> 
> * if only `iat` is defined, we set the `validFrom` to the value of `iat`
> * if both are defined, we set `validFrom` to the value of `nbf` (and lose the iat information in the VCDM2.0 representation)
> 
> So either remove nbf completely or make it optional and basically overwrite iat (for the VCDM2.0) if it exists? Does that make sense?

From the VCDM 2.0 spec:

> validFrom
A [credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-credential) MUST have an validFrom [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property). The value of the validFrom [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) MUST be a string value of an [[XMLSCHEMA11-2](https://www.w3.org/TR/xmlschema11-2/#dateTime)] combined date-time string representing the date and time the [credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-credential) becomes valid, which could be a date and time in the future. Note that this value represents the earliest point in time at which the information associated with the credentialSubject [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) becomes valid.

From the JWT nbf spec:

> The "nbf" (not before) claim identifies the time before which the JWT
   MUST NOT be accepted for processing.  The processing of the "nbf"
   claim requires that the current date/time MUST be after or equal to
   the not-before date/time listed in the "nbf" claim.  Implementers MAY
   provide for some small leeway, usually no more than a few minutes, to
   account for clock skew.  Its value MUST be a number containing a
   NumericDate value.  Use of this claim is OPTIONAL.

IMO, we should map nbf <-> validFrom and iat <-> issuedAt or we don't map iat at all (which might be fine).

**Comment by c2bo** [comment]
Hmm yeah, vc-jwt seems to do exactly that - drop `iat` and use `nbf` for `validFrom`.

**Comment by Sakurann** [comment]
I disagree. We don't have to follow VC-JWT mapping. The cleanest is to map iat to ValidFrom.

**Comment by c2bo** [comment]
> > I disagree with the request for changes. We don't have to follow VC-JWT mapping. The cleanest is to map iat to ValidFrom.
> 
> I see where you are coming from. Would you be ok with the following:
> 
> * make `nbf` optional
> * in the mapping section:
>   
>   * if `nbf` was omitted, use `iat` as default for `ValidFrom`
>   * if `nbf` is present, use `nbf` for `ValidFrom`
> 
> IMO, that would be the cleanest.

This feels more natural to me and is pretty much what I was thinking about 👍

**Comment by awoie** [comment]
Once PR #61 is merged, this should be included.

**Comment by awoie** [comment]
PR #61 got merged. closing this PR.

**Pull request closed without merging**
